export const projects = [
  {
    title: "StockWise",
    description:
      "Stock Market Tracker that lets you buy and sell stocks, view your portfolio, and get real-time stock prices.",
    image: "/stockwise.svg",
    link: "https://stockwise.sidlakhani.tech",
    github: "https://github.com/sid-lakhani/StockWise",
    category: ["Next.js", "React", "Tailwind CSS", "Clerk"],
  },
  {
    title: "TaskCanvas",
    description:
      "A basic To-Do website that allows user to add, delete and mark tasks as completed.",
    image: "/TaskCanvas.jpg",
    link: "https://taskcanvas.sidlakhani.tech",
    github: "https://github.com/sid-lakhani/TaskCanvas-Hackathon",
    category: ["Next.js", "React", "Tailwind CSS", "Firebase"],
  },
  {
    title: "Project 3",
    description: "Description of project 3",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 4",
    description: "Description of project 4",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 5",
    description: "Description of project 5",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 6",
    description: "Description of project 6",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 7",
    description: "Description of project 7",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 8",
    description: "Description of project 8",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 9",
    description: "Description of project 9",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
  {
    title: "Project 10",
    description: "Description of project 10",
    image: "/dummy.png",
    link: "",
    github: "",
    category: [],
  },
];
